<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Mappings\" />
    <Folder Include="Services\Implementations\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ZvitPlus.DAL\ZvitPlus.DAL.csproj" />
  </ItemGroup>

</Project>
