// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ZvitPlus.DAL.Context;

#nullable disable

namespace ZvitPlus.DAL.Migrations
{
    [DbContext(typeof(ZvitPlusDbContext))]
    [Migration("20251220025840_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("author");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("file_path");

                    b.Property<int>("FileSize")
                        .HasColumnType("int")
                        .HasColumnName("file_size");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasColumnName("name");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId")
                        .HasDatabaseName("idx_files_author_id");

                    b.ToTable("files", (string)null);
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.Report", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("file");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("idx_reports_file_id");

                    b.HasIndex("TemplateId")
                        .HasDatabaseName("idx_reports_template_id");

                    b.ToTable("reports", (string)null);
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.Template", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid>("FileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("file");

                    b.Property<Guid>("TemplateTypeId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("template_type");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique()
                        .HasDatabaseName("idx_templates_file_id");

                    b.HasIndex("TemplateTypeId")
                        .HasDatabaseName("idx_templates_template_type_id");

                    b.ToTable("templates", (string)null);
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.TemplateType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("idx_template_types_name");

                    b.ToTable("template_types", (string)null);
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("email");

                    b.Property<bool>("IsBanned")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false)
                        .HasColumnName("is_banned");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("varchar(64)")
                        .HasColumnName("login");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)")
                        .HasColumnName("password");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)")
                        .HasColumnName("role");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("idx_users_email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("idx_users_login");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.FileEntity", b =>
                {
                    b.HasOne("ZvitPlus.DAL.Models.Entities.User", "Author")
                        .WithMany("Files")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_files_users_author_id");

                    b.Navigation("Author");
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.Report", b =>
                {
                    b.HasOne("ZvitPlus.DAL.Models.Entities.FileEntity", "File")
                        .WithOne("Report")
                        .HasForeignKey("ZvitPlus.DAL.Models.Entities.Report", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_reports_files_id");

                    b.HasOne("ZvitPlus.DAL.Models.Entities.Template", "Template")
                        .WithMany("Reports")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_reports_templates_id");

                    b.Navigation("File");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.Template", b =>
                {
                    b.HasOne("ZvitPlus.DAL.Models.Entities.FileEntity", "File")
                        .WithOne("Template")
                        .HasForeignKey("ZvitPlus.DAL.Models.Entities.Template", "FileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_templates_files_id");

                    b.HasOne("ZvitPlus.DAL.Models.Entities.TemplateType", "TemplateType")
                        .WithMany("Templates")
                        .HasForeignKey("TemplateTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_templates_template_types_id");

                    b.Navigation("File");

                    b.Navigation("TemplateType");
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.FileEntity", b =>
                {
                    b.Navigation("Report");

                    b.Navigation("Template");
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.Template", b =>
                {
                    b.Navigation("Reports");
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.TemplateType", b =>
                {
                    b.Navigation("Templates");
                });

            modelBuilder.Entity("ZvitPlus.DAL.Models.Entities.User", b =>
                {
                    b.Navigation("Files");
                });
#pragma warning restore 612, 618
        }
    }
}
